import { createClient } from "@supabase/supabase-js";
import { defineTool, type ToolContext } from "@lovable.dev/mcp-js";
import { z } from "zod";

export default defineTool({
  name: "list_tasks",
  title: "Listar tarefas",
  description: "Lista tarefas do CRM visíveis ao usuário autenticado, com filtro opcional por status (pendente/concluida).",
  inputSchema: {
    status: z.enum(["pendente", "concluida"]).optional(),
    limit: z.number().int().min(1).max(200).optional(),
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, limit }, ctx: ToolContext) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Não autenticado." }], isError: true };
    }
    const supabase = createClient(
      process.env.SUPABASE_URL!,
      process.env.SUPABASE_PUBLISHABLE_KEY!,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false },
      },
    );
    const max = limit ?? 50;
    let q = supabase
      .from("tarefas")
      .select("id, lead_id, owner_id, title, due_date, done, auto_generated, kind")
      .order("due_date", { ascending: true })
      .limit(max);
    if (status === "pendente") q = q.eq("done", false);
    if (status === "concluida") q = q.eq("done", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: `Erro: ${error.message}` }], isError: true };
    const tasks = (data ?? []).map((t) => ({
      id: t.id,
      leadId: t.lead_id,
      ownerId: t.owner_id,
      title: t.title,
      dueDate: t.due_date,
      status: t.done ? "concluida" : "pendente",
      autoGenerated: t.auto_generated,
      kind: t.kind,
    }));
    return {
      content: [{ type: "text", text: `${tasks.length} tarefa(s).` }],
      structuredContent: { tasks },
    };
  },
});
