import { createClient } from "@supabase/supabase-js";
import { defineTool, type ToolContext } from "@lovable.dev/mcp-js";
import { z } from "zod";

export default defineTool({
  name: "list_tasks",
  title: "Listar tarefas",
  description:
    "Lista tarefas do CRM visíveis ao usuário autenticado (admin vê todas; vendedor vê as próprias). Retorna título, tipo, prioridade, status, vendedor, lead/cliente vinculado, data prevista e escalonamentos.",
  inputSchema: {
    status: z.enum(["pendente", "concluida", "adiada"]).optional(),
    tipo: z.string().optional().describe("Filtrar por tipo (ex: follow_up, cadencia_proposta, pos_venda_*)"),
    limit: z.number().int().min(1).max(200).optional(),
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ status, tipo, limit }, ctx: ToolContext) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Não autenticado." }], isError: true };
    }
    const supabase = createClient(
      process.env.SUPABASE_URL!,
      process.env.SUPABASE_PUBLISHABLE_KEY!,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false },
      },
    );
    const max = limit ?? 50;
    let q = supabase
      .from("tarefas")
      .select(
        "id, lead_id, owner_id, title, descricao, tipo, prioridade, status, origem, due_date, escalonamentos, auto_generated, concluida_at, nota_conclusao",
      )
      .order("due_date", { ascending: true })
      .limit(max);
    if (status) q = q.eq("status", status);
    if (tipo) q = q.eq("tipo", tipo);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: `Erro: ${error.message}` }], isError: true };

    const leadIds = Array.from(new Set((data ?? []).map((t) => t.lead_id).filter(Boolean))) as string[];
    const ownerIds = Array.from(new Set((data ?? []).map((t) => t.owner_id).filter(Boolean))) as string[];
    const [leadsRes, profsRes] = await Promise.all([
      leadIds.length
        ? supabase.from("leads").select("id, company, contact_name").in("id", leadIds)
        : Promise.resolve({ data: [] as any[] }),
      ownerIds.length
        ? supabase.from("profiles").select("id, name").in("id", ownerIds)
        : Promise.resolve({ data: [] as any[] }),
    ]);
    const leadsById = Object.fromEntries(((leadsRes.data as any[]) ?? []).map((l) => [l.id, l]));
    const ownersById = Object.fromEntries(((profsRes.data as any[]) ?? []).map((p) => [p.id, p.name ?? "—"]));

    const tasks = (data ?? []).map((t) => {
      const lead = t.lead_id ? leadsById[t.lead_id] : null;
      return {
        id: t.id,
        title: t.title,
        descricao: t.descricao,
        tipo: t.tipo,
        prioridade: t.prioridade,
        status: t.status,
        origem: t.origem,
        dueDate: t.due_date,
        escalonamentos: t.escalonamentos,
        autoGenerated: t.auto_generated,
        concluidaAt: t.concluida_at,
        notaConclusao: t.nota_conclusao,
        ownerId: t.owner_id,
        ownerName: t.owner_id ? ownersById[t.owner_id] ?? null : null,
        leadId: t.lead_id,
        leadCompany: lead?.company ?? null,
        leadContact: lead?.contact_name ?? null,
      };
    });

    const linhas = tasks.map((t) => {
      const due = t.dueDate ? new Date(t.dueDate).toLocaleString("pt-BR", { timeZone: "America/Sao_Paulo" }) : "—";
      const alvo = t.leadCompany ? ` · ${t.leadCompany}` : "";
      const esc = t.escalonamentos > 0 ? ` · esc:${t.escalonamentos}` : "";
      return `• [${t.status}] p${t.prioridade} ${t.title}${alvo} · ${t.ownerName ?? "—"} · ${due} · ${t.tipo ?? "—"}${esc}`;
    });
    return {
      content: [{ type: "text", text: `${tasks.length} tarefa(s).\n${linhas.join("\n")}` }],
      structuredContent: { tasks },
    };
  },
});
