/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as TrocarSenhaRouteImport } from './routes/trocar-senha'
import { Route as TransportadorasRouteImport } from './routes/transportadoras'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as TabelaPrecosRouteImport } from './routes/tabela-precos'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PlacarRouteImport } from './routes/placar'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as PedidosRouteImport } from './routes/pedidos'
import { Route as MinhaAgendaRouteImport } from './routes/minha-agenda'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as LicitacoesRouteImport } from './routes/licitacoes'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as FalhasRouteImport } from './routes/falhas'
import { Route as EstoqueRouteImport } from './routes/estoque'
import { Route as EmpresasRouteImport } from './routes/empresas'
import { Route as DefinirSenhaRouteImport } from './routes/definir-senha'
import { Route as ConversasRouteImport } from './routes/conversas'
import { Route as ContatosRouteImport } from './routes/contatos'
import { Route as CondicoesComerciaisRouteImport } from './routes/condicoes-comerciais'
import { Route as CanaisRouteImport } from './routes/canais'
import { Route as CadenciaSimuladorRouteImport } from './routes/cadencia-simulador'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AtendimentoIaRouteImport } from './routes/atendimento-ia'
import { Route as ArenaRouteImport } from './routes/arena'
import { Route as AgenteIaRouteImport } from './routes/agente-ia'
import { Route as AceitarConviteRouteImport } from './routes/aceitar-convite'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropostasIndexRouteImport } from './routes/propostas.index'
import { Route as ClientesIndexRouteImport } from './routes/clientes.index'
import { Route as PropostasIdRouteImport } from './routes/propostas.$id'
import { Route as PropostaPublicaIdRouteImport } from './routes/proposta-publica.$id'
import { Route as ClientesIdRouteImport } from './routes/clientes.$id'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as RomaneioPedidoIdTipoRouteImport } from './routes/romaneio.$pedidoId.$tipo'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as ApiPublicTelegramWebhookRouteImport } from './routes/api/public/telegram/webhook'
import { Route as ApiPublicHooksXerifeWatchdogConversaRouteImport } from './routes/api/public/hooks/xerife-watchdog-conversa'
import { Route as ApiPublicHooksXerifePedidosRouteImport } from './routes/api/public/hooks/xerife-pedidos'
import { Route as ApiPublicHooksXerifeFechamentoRouteImport } from './routes/api/public/hooks/xerife-fechamento'
import { Route as ApiPublicHooksXerifeEngineRouteImport } from './routes/api/public/hooks/xerife-engine'
import { Route as ApiPublicHooksXerifeCheckpointRouteImport } from './routes/api/public/hooks/xerife-checkpoint'
import { Route as ApiPublicHooksXerifeAgendaDiariaRouteImport } from './routes/api/public/hooks/xerife-agenda-diaria'
import { Route as ApiPublicHooksXerifeRouteImport } from './routes/api/public/hooks/xerife'
import { Route as ApiPublicHooksWhatsappCloudRouteImport } from './routes/api/public/hooks/whatsapp-cloud'
import { Route as ApiPublicHooksLeadExternoRouteImport } from './routes/api/public/hooks/lead-externo'
import { Route as ApiPublicHooksIaUrgenteRouteImport } from './routes/api/public/hooks/ia-urgente'
import { Route as ApiPublicHooksIaResponderRouteImport } from './routes/api/public/hooks/ia-responder'
import { Route as ApiPublicHooksIaQualificarRouteImport } from './routes/api/public/hooks/ia-qualificar'
import { Route as ApiPublicHooksIaHandoffRouteImport } from './routes/api/public/hooks/ia-handoff'
import { Route as ApiPublicHooksIaFilaEnvioRouteImport } from './routes/api/public/hooks/ia-fila-envio'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const TrocarSenhaRoute = TrocarSenhaRouteImport.update({
  id: '/trocar-senha',
  path: '/trocar-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const TransportadorasRoute = TransportadorasRouteImport.update({
  id: '/transportadoras',
  path: '/transportadoras',
  getParentRoute: () => rootRouteImport,
} as any)
const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const TabelaPrecosRoute = TabelaPrecosRouteImport.update({
  id: '/tabela-precos',
  path: '/tabela-precos',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PlacarRoute = PlacarRouteImport.update({
  id: '/placar',
  path: '/placar',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidosRoute = PedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const MinhaAgendaRoute = MinhaAgendaRouteImport.update({
  id: '/minha-agenda',
  path: '/minha-agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const LicitacoesRoute = LicitacoesRouteImport.update({
  id: '/licitacoes',
  path: '/licitacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const FalhasRoute = FalhasRouteImport.update({
  id: '/falhas',
  path: '/falhas',
  getParentRoute: () => rootRouteImport,
} as any)
const EstoqueRoute = EstoqueRouteImport.update({
  id: '/estoque',
  path: '/estoque',
  getParentRoute: () => rootRouteImport,
} as any)
const EmpresasRoute = EmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => rootRouteImport,
} as any)
const DefinirSenhaRoute = DefinirSenhaRouteImport.update({
  id: '/definir-senha',
  path: '/definir-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const ConversasRoute = ConversasRouteImport.update({
  id: '/conversas',
  path: '/conversas',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatosRoute = ContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const CondicoesComerciaisRoute = CondicoesComerciaisRouteImport.update({
  id: '/condicoes-comerciais',
  path: '/condicoes-comerciais',
  getParentRoute: () => rootRouteImport,
} as any)
const CanaisRoute = CanaisRouteImport.update({
  id: '/canais',
  path: '/canais',
  getParentRoute: () => rootRouteImport,
} as any)
const CadenciaSimuladorRoute = CadenciaSimuladorRouteImport.update({
  id: '/cadencia-simulador',
  path: '/cadencia-simulador',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AtendimentoIaRoute = AtendimentoIaRouteImport.update({
  id: '/atendimento-ia',
  path: '/atendimento-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const ArenaRoute = ArenaRouteImport.update({
  id: '/arena',
  path: '/arena',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenteIaRoute = AgenteIaRouteImport.update({
  id: '/agente-ia',
  path: '/agente-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const AceitarConviteRoute = AceitarConviteRouteImport.update({
  id: '/aceitar-convite',
  path: '/aceitar-convite',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasIndexRoute = PropostasIndexRouteImport.update({
  id: '/propostas/',
  path: '/propostas/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIndexRoute = ClientesIndexRouteImport.update({
  id: '/clientes/',
  path: '/clientes/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasIdRoute = PropostasIdRouteImport.update({
  id: '/propostas/$id',
  path: '/propostas/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostaPublicaIdRoute = PropostaPublicaIdRouteImport.update({
  id: '/proposta-publica/$id',
  path: '/proposta-publica/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientesIdRoute = ClientesIdRouteImport.update({
  id: '/clientes/$id',
  path: '/clientes/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const RomaneioPedidoIdTipoRoute = RomaneioPedidoIdTipoRouteImport.update({
  id: '/romaneio/$pedidoId/$tipo',
  path: '/romaneio/$pedidoId/$tipo',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicTelegramWebhookRoute =
  ApiPublicTelegramWebhookRouteImport.update({
    id: '/api/public/telegram/webhook',
    path: '/api/public/telegram/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksXerifeWatchdogConversaRoute =
  ApiPublicHooksXerifeWatchdogConversaRouteImport.update({
    id: '/api/public/hooks/xerife-watchdog-conversa',
    path: '/api/public/hooks/xerife-watchdog-conversa',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksXerifePedidosRoute =
  ApiPublicHooksXerifePedidosRouteImport.update({
    id: '/api/public/hooks/xerife-pedidos',
    path: '/api/public/hooks/xerife-pedidos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksXerifeFechamentoRoute =
  ApiPublicHooksXerifeFechamentoRouteImport.update({
    id: '/api/public/hooks/xerife-fechamento',
    path: '/api/public/hooks/xerife-fechamento',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksXerifeEngineRoute =
  ApiPublicHooksXerifeEngineRouteImport.update({
    id: '/api/public/hooks/xerife-engine',
    path: '/api/public/hooks/xerife-engine',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksXerifeCheckpointRoute =
  ApiPublicHooksXerifeCheckpointRouteImport.update({
    id: '/api/public/hooks/xerife-checkpoint',
    path: '/api/public/hooks/xerife-checkpoint',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksXerifeAgendaDiariaRoute =
  ApiPublicHooksXerifeAgendaDiariaRouteImport.update({
    id: '/api/public/hooks/xerife-agenda-diaria',
    path: '/api/public/hooks/xerife-agenda-diaria',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksXerifeRoute = ApiPublicHooksXerifeRouteImport.update({
  id: '/api/public/hooks/xerife',
  path: '/api/public/hooks/xerife',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksWhatsappCloudRoute =
  ApiPublicHooksWhatsappCloudRouteImport.update({
    id: '/api/public/hooks/whatsapp-cloud',
    path: '/api/public/hooks/whatsapp-cloud',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksLeadExternoRoute =
  ApiPublicHooksLeadExternoRouteImport.update({
    id: '/api/public/hooks/lead-externo',
    path: '/api/public/hooks/lead-externo',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksIaUrgenteRoute = ApiPublicHooksIaUrgenteRouteImport.update({
  id: '/api/public/hooks/ia-urgente',
  path: '/api/public/hooks/ia-urgente',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksIaResponderRoute =
  ApiPublicHooksIaResponderRouteImport.update({
    id: '/api/public/hooks/ia-responder',
    path: '/api/public/hooks/ia-responder',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksIaQualificarRoute =
  ApiPublicHooksIaQualificarRouteImport.update({
    id: '/api/public/hooks/ia-qualificar',
    path: '/api/public/hooks/ia-qualificar',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicHooksIaHandoffRoute = ApiPublicHooksIaHandoffRouteImport.update({
  id: '/api/public/hooks/ia-handoff',
  path: '/api/public/hooks/ia-handoff',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHooksIaFilaEnvioRoute =
  ApiPublicHooksIaFilaEnvioRouteImport.update({
    id: '/api/public/hooks/ia-fila-envio',
    path: '/api/public/hooks/ia-fila-envio',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/agente-ia': typeof AgenteIaRoute
  '/arena': typeof ArenaRoute
  '/atendimento-ia': typeof AtendimentoIaRoute
  '/auth': typeof AuthRoute
  '/cadencia-simulador': typeof CadenciaSimuladorRoute
  '/canais': typeof CanaisRoute
  '/condicoes-comerciais': typeof CondicoesComerciaisRoute
  '/contatos': typeof ContatosRoute
  '/conversas': typeof ConversasRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/empresas': typeof EmpresasRoute
  '/estoque': typeof EstoqueRoute
  '/falhas': typeof FalhasRoute
  '/leads': typeof LeadsRoute
  '/licitacoes': typeof LicitacoesRoute
  '/mcp': typeof McpRoute
  '/minha-agenda': typeof MinhaAgendaRoute
  '/pedidos': typeof PedidosRoute
  '/pipeline': typeof PipelineRoute
  '/placar': typeof PlacarRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/tabela-precos': typeof TabelaPrecosRoute
  '/tarefas': typeof TarefasRoute
  '/transportadoras': typeof TransportadorasRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/usuarios': typeof UsuariosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/proposta-publica/$id': typeof PropostaPublicaIdRoute
  '/propostas/$id': typeof PropostasIdRoute
  '/clientes/': typeof ClientesIndexRoute
  '/propostas/': typeof PropostasIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/romaneio/$pedidoId/$tipo': typeof RomaneioPedidoIdTipoRoute
  '/api/public/hooks/ia-fila-envio': typeof ApiPublicHooksIaFilaEnvioRoute
  '/api/public/hooks/ia-handoff': typeof ApiPublicHooksIaHandoffRoute
  '/api/public/hooks/ia-qualificar': typeof ApiPublicHooksIaQualificarRoute
  '/api/public/hooks/ia-responder': typeof ApiPublicHooksIaResponderRoute
  '/api/public/hooks/ia-urgente': typeof ApiPublicHooksIaUrgenteRoute
  '/api/public/hooks/lead-externo': typeof ApiPublicHooksLeadExternoRoute
  '/api/public/hooks/whatsapp-cloud': typeof ApiPublicHooksWhatsappCloudRoute
  '/api/public/hooks/xerife': typeof ApiPublicHooksXerifeRoute
  '/api/public/hooks/xerife-agenda-diaria': typeof ApiPublicHooksXerifeAgendaDiariaRoute
  '/api/public/hooks/xerife-checkpoint': typeof ApiPublicHooksXerifeCheckpointRoute
  '/api/public/hooks/xerife-engine': typeof ApiPublicHooksXerifeEngineRoute
  '/api/public/hooks/xerife-fechamento': typeof ApiPublicHooksXerifeFechamentoRoute
  '/api/public/hooks/xerife-pedidos': typeof ApiPublicHooksXerifePedidosRoute
  '/api/public/hooks/xerife-watchdog-conversa': typeof ApiPublicHooksXerifeWatchdogConversaRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/agente-ia': typeof AgenteIaRoute
  '/arena': typeof ArenaRoute
  '/atendimento-ia': typeof AtendimentoIaRoute
  '/auth': typeof AuthRoute
  '/cadencia-simulador': typeof CadenciaSimuladorRoute
  '/canais': typeof CanaisRoute
  '/condicoes-comerciais': typeof CondicoesComerciaisRoute
  '/contatos': typeof ContatosRoute
  '/conversas': typeof ConversasRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/empresas': typeof EmpresasRoute
  '/estoque': typeof EstoqueRoute
  '/falhas': typeof FalhasRoute
  '/leads': typeof LeadsRoute
  '/licitacoes': typeof LicitacoesRoute
  '/mcp': typeof McpRoute
  '/minha-agenda': typeof MinhaAgendaRoute
  '/pedidos': typeof PedidosRoute
  '/pipeline': typeof PipelineRoute
  '/placar': typeof PlacarRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/tabela-precos': typeof TabelaPrecosRoute
  '/tarefas': typeof TarefasRoute
  '/transportadoras': typeof TransportadorasRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/usuarios': typeof UsuariosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/proposta-publica/$id': typeof PropostaPublicaIdRoute
  '/propostas/$id': typeof PropostasIdRoute
  '/clientes': typeof ClientesIndexRoute
  '/propostas': typeof PropostasIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/romaneio/$pedidoId/$tipo': typeof RomaneioPedidoIdTipoRoute
  '/api/public/hooks/ia-fila-envio': typeof ApiPublicHooksIaFilaEnvioRoute
  '/api/public/hooks/ia-handoff': typeof ApiPublicHooksIaHandoffRoute
  '/api/public/hooks/ia-qualificar': typeof ApiPublicHooksIaQualificarRoute
  '/api/public/hooks/ia-responder': typeof ApiPublicHooksIaResponderRoute
  '/api/public/hooks/ia-urgente': typeof ApiPublicHooksIaUrgenteRoute
  '/api/public/hooks/lead-externo': typeof ApiPublicHooksLeadExternoRoute
  '/api/public/hooks/whatsapp-cloud': typeof ApiPublicHooksWhatsappCloudRoute
  '/api/public/hooks/xerife': typeof ApiPublicHooksXerifeRoute
  '/api/public/hooks/xerife-agenda-diaria': typeof ApiPublicHooksXerifeAgendaDiariaRoute
  '/api/public/hooks/xerife-checkpoint': typeof ApiPublicHooksXerifeCheckpointRoute
  '/api/public/hooks/xerife-engine': typeof ApiPublicHooksXerifeEngineRoute
  '/api/public/hooks/xerife-fechamento': typeof ApiPublicHooksXerifeFechamentoRoute
  '/api/public/hooks/xerife-pedidos': typeof ApiPublicHooksXerifePedidosRoute
  '/api/public/hooks/xerife-watchdog-conversa': typeof ApiPublicHooksXerifeWatchdogConversaRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/aceitar-convite': typeof AceitarConviteRoute
  '/agente-ia': typeof AgenteIaRoute
  '/arena': typeof ArenaRoute
  '/atendimento-ia': typeof AtendimentoIaRoute
  '/auth': typeof AuthRoute
  '/cadencia-simulador': typeof CadenciaSimuladorRoute
  '/canais': typeof CanaisRoute
  '/condicoes-comerciais': typeof CondicoesComerciaisRoute
  '/contatos': typeof ContatosRoute
  '/conversas': typeof ConversasRoute
  '/definir-senha': typeof DefinirSenhaRoute
  '/empresas': typeof EmpresasRoute
  '/estoque': typeof EstoqueRoute
  '/falhas': typeof FalhasRoute
  '/leads': typeof LeadsRoute
  '/licitacoes': typeof LicitacoesRoute
  '/mcp': typeof McpRoute
  '/minha-agenda': typeof MinhaAgendaRoute
  '/pedidos': typeof PedidosRoute
  '/pipeline': typeof PipelineRoute
  '/placar': typeof PlacarRoute
  '/produtos': typeof ProdutosRoute
  '/relatorios': typeof RelatoriosRoute
  '/tabela-precos': typeof TabelaPrecosRoute
  '/tarefas': typeof TarefasRoute
  '/transportadoras': typeof TransportadorasRoute
  '/trocar-senha': typeof TrocarSenhaRoute
  '/usuarios': typeof UsuariosRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/clientes/$id': typeof ClientesIdRoute
  '/proposta-publica/$id': typeof PropostaPublicaIdRoute
  '/propostas/$id': typeof PropostasIdRoute
  '/clientes/': typeof ClientesIndexRoute
  '/propostas/': typeof PropostasIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/romaneio/$pedidoId/$tipo': typeof RomaneioPedidoIdTipoRoute
  '/api/public/hooks/ia-fila-envio': typeof ApiPublicHooksIaFilaEnvioRoute
  '/api/public/hooks/ia-handoff': typeof ApiPublicHooksIaHandoffRoute
  '/api/public/hooks/ia-qualificar': typeof ApiPublicHooksIaQualificarRoute
  '/api/public/hooks/ia-responder': typeof ApiPublicHooksIaResponderRoute
  '/api/public/hooks/ia-urgente': typeof ApiPublicHooksIaUrgenteRoute
  '/api/public/hooks/lead-externo': typeof ApiPublicHooksLeadExternoRoute
  '/api/public/hooks/whatsapp-cloud': typeof ApiPublicHooksWhatsappCloudRoute
  '/api/public/hooks/xerife': typeof ApiPublicHooksXerifeRoute
  '/api/public/hooks/xerife-agenda-diaria': typeof ApiPublicHooksXerifeAgendaDiariaRoute
  '/api/public/hooks/xerife-checkpoint': typeof ApiPublicHooksXerifeCheckpointRoute
  '/api/public/hooks/xerife-engine': typeof ApiPublicHooksXerifeEngineRoute
  '/api/public/hooks/xerife-fechamento': typeof ApiPublicHooksXerifeFechamentoRoute
  '/api/public/hooks/xerife-pedidos': typeof ApiPublicHooksXerifePedidosRoute
  '/api/public/hooks/xerife-watchdog-conversa': typeof ApiPublicHooksXerifeWatchdogConversaRoute
  '/api/public/telegram/webhook': typeof ApiPublicTelegramWebhookRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/aceitar-convite'
    | '/agente-ia'
    | '/arena'
    | '/atendimento-ia'
    | '/auth'
    | '/cadencia-simulador'
    | '/canais'
    | '/condicoes-comerciais'
    | '/contatos'
    | '/conversas'
    | '/definir-senha'
    | '/empresas'
    | '/estoque'
    | '/falhas'
    | '/leads'
    | '/licitacoes'
    | '/mcp'
    | '/minha-agenda'
    | '/pedidos'
    | '/pipeline'
    | '/placar'
    | '/produtos'
    | '/relatorios'
    | '/tabela-precos'
    | '/tarefas'
    | '/transportadoras'
    | '/trocar-senha'
    | '/usuarios'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/clientes/$id'
    | '/proposta-publica/$id'
    | '/propostas/$id'
    | '/clientes/'
    | '/propostas/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/romaneio/$pedidoId/$tipo'
    | '/api/public/hooks/ia-fila-envio'
    | '/api/public/hooks/ia-handoff'
    | '/api/public/hooks/ia-qualificar'
    | '/api/public/hooks/ia-responder'
    | '/api/public/hooks/ia-urgente'
    | '/api/public/hooks/lead-externo'
    | '/api/public/hooks/whatsapp-cloud'
    | '/api/public/hooks/xerife'
    | '/api/public/hooks/xerife-agenda-diaria'
    | '/api/public/hooks/xerife-checkpoint'
    | '/api/public/hooks/xerife-engine'
    | '/api/public/hooks/xerife-fechamento'
    | '/api/public/hooks/xerife-pedidos'
    | '/api/public/hooks/xerife-watchdog-conversa'
    | '/api/public/telegram/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/aceitar-convite'
    | '/agente-ia'
    | '/arena'
    | '/atendimento-ia'
    | '/auth'
    | '/cadencia-simulador'
    | '/canais'
    | '/condicoes-comerciais'
    | '/contatos'
    | '/conversas'
    | '/definir-senha'
    | '/empresas'
    | '/estoque'
    | '/falhas'
    | '/leads'
    | '/licitacoes'
    | '/mcp'
    | '/minha-agenda'
    | '/pedidos'
    | '/pipeline'
    | '/placar'
    | '/produtos'
    | '/relatorios'
    | '/tabela-precos'
    | '/tarefas'
    | '/transportadoras'
    | '/trocar-senha'
    | '/usuarios'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/clientes/$id'
    | '/proposta-publica/$id'
    | '/propostas/$id'
    | '/clientes'
    | '/propostas'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/romaneio/$pedidoId/$tipo'
    | '/api/public/hooks/ia-fila-envio'
    | '/api/public/hooks/ia-handoff'
    | '/api/public/hooks/ia-qualificar'
    | '/api/public/hooks/ia-responder'
    | '/api/public/hooks/ia-urgente'
    | '/api/public/hooks/lead-externo'
    | '/api/public/hooks/whatsapp-cloud'
    | '/api/public/hooks/xerife'
    | '/api/public/hooks/xerife-agenda-diaria'
    | '/api/public/hooks/xerife-checkpoint'
    | '/api/public/hooks/xerife-engine'
    | '/api/public/hooks/xerife-fechamento'
    | '/api/public/hooks/xerife-pedidos'
    | '/api/public/hooks/xerife-watchdog-conversa'
    | '/api/public/telegram/webhook'
    | '/lovable/email/transactional/preview'
  id:
    | '__root__'
    | '/'
    | '/aceitar-convite'
    | '/agente-ia'
    | '/arena'
    | '/atendimento-ia'
    | '/auth'
    | '/cadencia-simulador'
    | '/canais'
    | '/condicoes-comerciais'
    | '/contatos'
    | '/conversas'
    | '/definir-senha'
    | '/empresas'
    | '/estoque'
    | '/falhas'
    | '/leads'
    | '/licitacoes'
    | '/mcp'
    | '/minha-agenda'
    | '/pedidos'
    | '/pipeline'
    | '/placar'
    | '/produtos'
    | '/relatorios'
    | '/tabela-precos'
    | '/tarefas'
    | '/transportadoras'
    | '/trocar-senha'
    | '/usuarios'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/clientes/$id'
    | '/proposta-publica/$id'
    | '/propostas/$id'
    | '/clientes/'
    | '/propostas/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/romaneio/$pedidoId/$tipo'
    | '/api/public/hooks/ia-fila-envio'
    | '/api/public/hooks/ia-handoff'
    | '/api/public/hooks/ia-qualificar'
    | '/api/public/hooks/ia-responder'
    | '/api/public/hooks/ia-urgente'
    | '/api/public/hooks/lead-externo'
    | '/api/public/hooks/whatsapp-cloud'
    | '/api/public/hooks/xerife'
    | '/api/public/hooks/xerife-agenda-diaria'
    | '/api/public/hooks/xerife-checkpoint'
    | '/api/public/hooks/xerife-engine'
    | '/api/public/hooks/xerife-fechamento'
    | '/api/public/hooks/xerife-pedidos'
    | '/api/public/hooks/xerife-watchdog-conversa'
    | '/api/public/telegram/webhook'
    | '/lovable/email/transactional/preview'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AceitarConviteRoute: typeof AceitarConviteRoute
  AgenteIaRoute: typeof AgenteIaRoute
  ArenaRoute: typeof ArenaRoute
  AtendimentoIaRoute: typeof AtendimentoIaRoute
  AuthRoute: typeof AuthRoute
  CadenciaSimuladorRoute: typeof CadenciaSimuladorRoute
  CanaisRoute: typeof CanaisRoute
  CondicoesComerciaisRoute: typeof CondicoesComerciaisRoute
  ContatosRoute: typeof ContatosRoute
  ConversasRoute: typeof ConversasRoute
  DefinirSenhaRoute: typeof DefinirSenhaRoute
  EmpresasRoute: typeof EmpresasRoute
  EstoqueRoute: typeof EstoqueRoute
  FalhasRoute: typeof FalhasRoute
  LeadsRoute: typeof LeadsRoute
  LicitacoesRoute: typeof LicitacoesRoute
  McpRoute: typeof McpRoute
  MinhaAgendaRoute: typeof MinhaAgendaRoute
  PedidosRoute: typeof PedidosRoute
  PipelineRoute: typeof PipelineRoute
  PlacarRoute: typeof PlacarRoute
  ProdutosRoute: typeof ProdutosRoute
  RelatoriosRoute: typeof RelatoriosRoute
  TabelaPrecosRoute: typeof TabelaPrecosRoute
  TarefasRoute: typeof TarefasRoute
  TransportadorasRoute: typeof TransportadorasRoute
  TrocarSenhaRoute: typeof TrocarSenhaRoute
  UsuariosRoute: typeof UsuariosRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  ClientesIdRoute: typeof ClientesIdRoute
  PropostaPublicaIdRoute: typeof PropostaPublicaIdRoute
  PropostasIdRoute: typeof PropostasIdRoute
  ClientesIndexRoute: typeof ClientesIndexRoute
  PropostasIndexRoute: typeof PropostasIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  RomaneioPedidoIdTipoRoute: typeof RomaneioPedidoIdTipoRoute
  ApiPublicHooksIaFilaEnvioRoute: typeof ApiPublicHooksIaFilaEnvioRoute
  ApiPublicHooksIaHandoffRoute: typeof ApiPublicHooksIaHandoffRoute
  ApiPublicHooksIaQualificarRoute: typeof ApiPublicHooksIaQualificarRoute
  ApiPublicHooksIaResponderRoute: typeof ApiPublicHooksIaResponderRoute
  ApiPublicHooksIaUrgenteRoute: typeof ApiPublicHooksIaUrgenteRoute
  ApiPublicHooksLeadExternoRoute: typeof ApiPublicHooksLeadExternoRoute
  ApiPublicHooksWhatsappCloudRoute: typeof ApiPublicHooksWhatsappCloudRoute
  ApiPublicHooksXerifeRoute: typeof ApiPublicHooksXerifeRoute
  ApiPublicHooksXerifeAgendaDiariaRoute: typeof ApiPublicHooksXerifeAgendaDiariaRoute
  ApiPublicHooksXerifeCheckpointRoute: typeof ApiPublicHooksXerifeCheckpointRoute
  ApiPublicHooksXerifeEngineRoute: typeof ApiPublicHooksXerifeEngineRoute
  ApiPublicHooksXerifeFechamentoRoute: typeof ApiPublicHooksXerifeFechamentoRoute
  ApiPublicHooksXerifePedidosRoute: typeof ApiPublicHooksXerifePedidosRoute
  ApiPublicHooksXerifeWatchdogConversaRoute: typeof ApiPublicHooksXerifeWatchdogConversaRoute
  ApiPublicTelegramWebhookRoute: typeof ApiPublicTelegramWebhookRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trocar-senha': {
      id: '/trocar-senha'
      path: '/trocar-senha'
      fullPath: '/trocar-senha'
      preLoaderRoute: typeof TrocarSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transportadoras': {
      id: '/transportadoras'
      path: '/transportadoras'
      fullPath: '/transportadoras'
      preLoaderRoute: typeof TransportadorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tabela-precos': {
      id: '/tabela-precos'
      path: '/tabela-precos'
      fullPath: '/tabela-precos'
      preLoaderRoute: typeof TabelaPrecosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/placar': {
      id: '/placar'
      path: '/placar'
      fullPath: '/placar'
      preLoaderRoute: typeof PlacarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedidos': {
      id: '/pedidos'
      path: '/pedidos'
      fullPath: '/pedidos'
      preLoaderRoute: typeof PedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/minha-agenda': {
      id: '/minha-agenda'
      path: '/minha-agenda'
      fullPath: '/minha-agenda'
      preLoaderRoute: typeof MinhaAgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/licitacoes': {
      id: '/licitacoes'
      path: '/licitacoes'
      fullPath: '/licitacoes'
      preLoaderRoute: typeof LicitacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/falhas': {
      id: '/falhas'
      path: '/falhas'
      fullPath: '/falhas'
      preLoaderRoute: typeof FalhasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/estoque': {
      id: '/estoque'
      path: '/estoque'
      fullPath: '/estoque'
      preLoaderRoute: typeof EstoqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/empresas': {
      id: '/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof EmpresasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/definir-senha': {
      id: '/definir-senha'
      path: '/definir-senha'
      fullPath: '/definir-senha'
      preLoaderRoute: typeof DefinirSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conversas': {
      id: '/conversas'
      path: '/conversas'
      fullPath: '/conversas'
      preLoaderRoute: typeof ConversasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatos': {
      id: '/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof ContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/condicoes-comerciais': {
      id: '/condicoes-comerciais'
      path: '/condicoes-comerciais'
      fullPath: '/condicoes-comerciais'
      preLoaderRoute: typeof CondicoesComerciaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canais': {
      id: '/canais'
      path: '/canais'
      fullPath: '/canais'
      preLoaderRoute: typeof CanaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadencia-simulador': {
      id: '/cadencia-simulador'
      path: '/cadencia-simulador'
      fullPath: '/cadencia-simulador'
      preLoaderRoute: typeof CadenciaSimuladorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atendimento-ia': {
      id: '/atendimento-ia'
      path: '/atendimento-ia'
      fullPath: '/atendimento-ia'
      preLoaderRoute: typeof AtendimentoIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arena': {
      id: '/arena'
      path: '/arena'
      fullPath: '/arena'
      preLoaderRoute: typeof ArenaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agente-ia': {
      id: '/agente-ia'
      path: '/agente-ia'
      fullPath: '/agente-ia'
      preLoaderRoute: typeof AgenteIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aceitar-convite': {
      id: '/aceitar-convite'
      path: '/aceitar-convite'
      fullPath: '/aceitar-convite'
      preLoaderRoute: typeof AceitarConviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas/': {
      id: '/propostas/'
      path: '/propostas'
      fullPath: '/propostas/'
      preLoaderRoute: typeof PropostasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/': {
      id: '/clientes/'
      path: '/clientes'
      fullPath: '/clientes/'
      preLoaderRoute: typeof ClientesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas/$id': {
      id: '/propostas/$id'
      path: '/propostas/$id'
      fullPath: '/propostas/$id'
      preLoaderRoute: typeof PropostasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposta-publica/$id': {
      id: '/proposta-publica/$id'
      path: '/proposta-publica/$id'
      fullPath: '/proposta-publica/$id'
      preLoaderRoute: typeof PropostaPublicaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clientes/$id': {
      id: '/clientes/$id'
      path: '/clientes/$id'
      fullPath: '/clientes/$id'
      preLoaderRoute: typeof ClientesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/romaneio/$pedidoId/$tipo': {
      id: '/romaneio/$pedidoId/$tipo'
      path: '/romaneio/$pedidoId/$tipo'
      fullPath: '/romaneio/$pedidoId/$tipo'
      preLoaderRoute: typeof RomaneioPedidoIdTipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/telegram/webhook': {
      id: '/api/public/telegram/webhook'
      path: '/api/public/telegram/webhook'
      fullPath: '/api/public/telegram/webhook'
      preLoaderRoute: typeof ApiPublicTelegramWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/xerife-watchdog-conversa': {
      id: '/api/public/hooks/xerife-watchdog-conversa'
      path: '/api/public/hooks/xerife-watchdog-conversa'
      fullPath: '/api/public/hooks/xerife-watchdog-conversa'
      preLoaderRoute: typeof ApiPublicHooksXerifeWatchdogConversaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/xerife-pedidos': {
      id: '/api/public/hooks/xerife-pedidos'
      path: '/api/public/hooks/xerife-pedidos'
      fullPath: '/api/public/hooks/xerife-pedidos'
      preLoaderRoute: typeof ApiPublicHooksXerifePedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/xerife-fechamento': {
      id: '/api/public/hooks/xerife-fechamento'
      path: '/api/public/hooks/xerife-fechamento'
      fullPath: '/api/public/hooks/xerife-fechamento'
      preLoaderRoute: typeof ApiPublicHooksXerifeFechamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/xerife-engine': {
      id: '/api/public/hooks/xerife-engine'
      path: '/api/public/hooks/xerife-engine'
      fullPath: '/api/public/hooks/xerife-engine'
      preLoaderRoute: typeof ApiPublicHooksXerifeEngineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/xerife-checkpoint': {
      id: '/api/public/hooks/xerife-checkpoint'
      path: '/api/public/hooks/xerife-checkpoint'
      fullPath: '/api/public/hooks/xerife-checkpoint'
      preLoaderRoute: typeof ApiPublicHooksXerifeCheckpointRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/xerife-agenda-diaria': {
      id: '/api/public/hooks/xerife-agenda-diaria'
      path: '/api/public/hooks/xerife-agenda-diaria'
      fullPath: '/api/public/hooks/xerife-agenda-diaria'
      preLoaderRoute: typeof ApiPublicHooksXerifeAgendaDiariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/xerife': {
      id: '/api/public/hooks/xerife'
      path: '/api/public/hooks/xerife'
      fullPath: '/api/public/hooks/xerife'
      preLoaderRoute: typeof ApiPublicHooksXerifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/whatsapp-cloud': {
      id: '/api/public/hooks/whatsapp-cloud'
      path: '/api/public/hooks/whatsapp-cloud'
      fullPath: '/api/public/hooks/whatsapp-cloud'
      preLoaderRoute: typeof ApiPublicHooksWhatsappCloudRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/lead-externo': {
      id: '/api/public/hooks/lead-externo'
      path: '/api/public/hooks/lead-externo'
      fullPath: '/api/public/hooks/lead-externo'
      preLoaderRoute: typeof ApiPublicHooksLeadExternoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ia-urgente': {
      id: '/api/public/hooks/ia-urgente'
      path: '/api/public/hooks/ia-urgente'
      fullPath: '/api/public/hooks/ia-urgente'
      preLoaderRoute: typeof ApiPublicHooksIaUrgenteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ia-responder': {
      id: '/api/public/hooks/ia-responder'
      path: '/api/public/hooks/ia-responder'
      fullPath: '/api/public/hooks/ia-responder'
      preLoaderRoute: typeof ApiPublicHooksIaResponderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ia-qualificar': {
      id: '/api/public/hooks/ia-qualificar'
      path: '/api/public/hooks/ia-qualificar'
      fullPath: '/api/public/hooks/ia-qualificar'
      preLoaderRoute: typeof ApiPublicHooksIaQualificarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ia-handoff': {
      id: '/api/public/hooks/ia-handoff'
      path: '/api/public/hooks/ia-handoff'
      fullPath: '/api/public/hooks/ia-handoff'
      preLoaderRoute: typeof ApiPublicHooksIaHandoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/hooks/ia-fila-envio': {
      id: '/api/public/hooks/ia-fila-envio'
      path: '/api/public/hooks/ia-fila-envio'
      fullPath: '/api/public/hooks/ia-fila-envio'
      preLoaderRoute: typeof ApiPublicHooksIaFilaEnvioRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AceitarConviteRoute: AceitarConviteRoute,
  AgenteIaRoute: AgenteIaRoute,
  ArenaRoute: ArenaRoute,
  AtendimentoIaRoute: AtendimentoIaRoute,
  AuthRoute: AuthRoute,
  CadenciaSimuladorRoute: CadenciaSimuladorRoute,
  CanaisRoute: CanaisRoute,
  CondicoesComerciaisRoute: CondicoesComerciaisRoute,
  ContatosRoute: ContatosRoute,
  ConversasRoute: ConversasRoute,
  DefinirSenhaRoute: DefinirSenhaRoute,
  EmpresasRoute: EmpresasRoute,
  EstoqueRoute: EstoqueRoute,
  FalhasRoute: FalhasRoute,
  LeadsRoute: LeadsRoute,
  LicitacoesRoute: LicitacoesRoute,
  McpRoute: McpRoute,
  MinhaAgendaRoute: MinhaAgendaRoute,
  PedidosRoute: PedidosRoute,
  PipelineRoute: PipelineRoute,
  PlacarRoute: PlacarRoute,
  ProdutosRoute: ProdutosRoute,
  RelatoriosRoute: RelatoriosRoute,
  TabelaPrecosRoute: TabelaPrecosRoute,
  TarefasRoute: TarefasRoute,
  TransportadorasRoute: TransportadorasRoute,
  TrocarSenhaRoute: TrocarSenhaRoute,
  UsuariosRoute: UsuariosRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  ClientesIdRoute: ClientesIdRoute,
  PropostaPublicaIdRoute: PropostaPublicaIdRoute,
  PropostasIdRoute: PropostasIdRoute,
  ClientesIndexRoute: ClientesIndexRoute,
  PropostasIndexRoute: PropostasIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  RomaneioPedidoIdTipoRoute: RomaneioPedidoIdTipoRoute,
  ApiPublicHooksIaFilaEnvioRoute: ApiPublicHooksIaFilaEnvioRoute,
  ApiPublicHooksIaHandoffRoute: ApiPublicHooksIaHandoffRoute,
  ApiPublicHooksIaQualificarRoute: ApiPublicHooksIaQualificarRoute,
  ApiPublicHooksIaResponderRoute: ApiPublicHooksIaResponderRoute,
  ApiPublicHooksIaUrgenteRoute: ApiPublicHooksIaUrgenteRoute,
  ApiPublicHooksLeadExternoRoute: ApiPublicHooksLeadExternoRoute,
  ApiPublicHooksWhatsappCloudRoute: ApiPublicHooksWhatsappCloudRoute,
  ApiPublicHooksXerifeRoute: ApiPublicHooksXerifeRoute,
  ApiPublicHooksXerifeAgendaDiariaRoute: ApiPublicHooksXerifeAgendaDiariaRoute,
  ApiPublicHooksXerifeCheckpointRoute: ApiPublicHooksXerifeCheckpointRoute,
  ApiPublicHooksXerifeEngineRoute: ApiPublicHooksXerifeEngineRoute,
  ApiPublicHooksXerifeFechamentoRoute: ApiPublicHooksXerifeFechamentoRoute,
  ApiPublicHooksXerifePedidosRoute: ApiPublicHooksXerifePedidosRoute,
  ApiPublicHooksXerifeWatchdogConversaRoute:
    ApiPublicHooksXerifeWatchdogConversaRoute,
  ApiPublicTelegramWebhookRoute: ApiPublicTelegramWebhookRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
