/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TarefasRouteImport } from './routes/tarefas'
import { Route as ProdutosRouteImport } from './routes/produtos'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as ContatosRouteImport } from './routes/contatos'
import { Route as CondicoesComerciaisRouteImport } from './routes/condicoes-comerciais'
import { Route as CanaisRouteImport } from './routes/canais'
import { Route as AgenteIaRouteImport } from './routes/agente-ia'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropostasIndexRouteImport } from './routes/propostas.index'
import { Route as PropostasIdRouteImport } from './routes/propostas.$id'

const TarefasRoute = TarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => rootRouteImport,
} as any)
const ProdutosRoute = ProdutosRouteImport.update({
  id: '/produtos',
  path: '/produtos',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatosRoute = ContatosRouteImport.update({
  id: '/contatos',
  path: '/contatos',
  getParentRoute: () => rootRouteImport,
} as any)
const CondicoesComerciaisRoute = CondicoesComerciaisRouteImport.update({
  id: '/condicoes-comerciais',
  path: '/condicoes-comerciais',
  getParentRoute: () => rootRouteImport,
} as any)
const CanaisRoute = CanaisRouteImport.update({
  id: '/canais',
  path: '/canais',
  getParentRoute: () => rootRouteImport,
} as any)
const AgenteIaRoute = AgenteIaRouteImport.update({
  id: '/agente-ia',
  path: '/agente-ia',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasIndexRoute = PropostasIndexRouteImport.update({
  id: '/propostas/',
  path: '/propostas/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropostasIdRoute = PropostasIdRouteImport.update({
  id: '/propostas/$id',
  path: '/propostas/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agente-ia': typeof AgenteIaRoute
  '/canais': typeof CanaisRoute
  '/condicoes-comerciais': typeof CondicoesComerciaisRoute
  '/contatos': typeof ContatosRoute
  '/pipeline': typeof PipelineRoute
  '/produtos': typeof ProdutosRoute
  '/tarefas': typeof TarefasRoute
  '/propostas/$id': typeof PropostasIdRoute
  '/propostas/': typeof PropostasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agente-ia': typeof AgenteIaRoute
  '/canais': typeof CanaisRoute
  '/condicoes-comerciais': typeof CondicoesComerciaisRoute
  '/contatos': typeof ContatosRoute
  '/pipeline': typeof PipelineRoute
  '/produtos': typeof ProdutosRoute
  '/tarefas': typeof TarefasRoute
  '/propostas/$id': typeof PropostasIdRoute
  '/propostas': typeof PropostasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agente-ia': typeof AgenteIaRoute
  '/canais': typeof CanaisRoute
  '/condicoes-comerciais': typeof CondicoesComerciaisRoute
  '/contatos': typeof ContatosRoute
  '/pipeline': typeof PipelineRoute
  '/produtos': typeof ProdutosRoute
  '/tarefas': typeof TarefasRoute
  '/propostas/$id': typeof PropostasIdRoute
  '/propostas/': typeof PropostasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agente-ia'
    | '/canais'
    | '/condicoes-comerciais'
    | '/contatos'
    | '/pipeline'
    | '/produtos'
    | '/tarefas'
    | '/propostas/$id'
    | '/propostas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agente-ia'
    | '/canais'
    | '/condicoes-comerciais'
    | '/contatos'
    | '/pipeline'
    | '/produtos'
    | '/tarefas'
    | '/propostas/$id'
    | '/propostas'
  id:
    | '__root__'
    | '/'
    | '/agente-ia'
    | '/canais'
    | '/condicoes-comerciais'
    | '/contatos'
    | '/pipeline'
    | '/produtos'
    | '/tarefas'
    | '/propostas/$id'
    | '/propostas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgenteIaRoute: typeof AgenteIaRoute
  CanaisRoute: typeof CanaisRoute
  CondicoesComerciaisRoute: typeof CondicoesComerciaisRoute
  ContatosRoute: typeof ContatosRoute
  PipelineRoute: typeof PipelineRoute
  ProdutosRoute: typeof ProdutosRoute
  TarefasRoute: typeof TarefasRoute
  PropostasIdRoute: typeof PropostasIdRoute
  PropostasIndexRoute: typeof PropostasIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tarefas': {
      id: '/tarefas'
      path: '/tarefas'
      fullPath: '/tarefas'
      preLoaderRoute: typeof TarefasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/produtos': {
      id: '/produtos'
      path: '/produtos'
      fullPath: '/produtos'
      preLoaderRoute: typeof ProdutosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contatos': {
      id: '/contatos'
      path: '/contatos'
      fullPath: '/contatos'
      preLoaderRoute: typeof ContatosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/condicoes-comerciais': {
      id: '/condicoes-comerciais'
      path: '/condicoes-comerciais'
      fullPath: '/condicoes-comerciais'
      preLoaderRoute: typeof CondicoesComerciaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canais': {
      id: '/canais'
      path: '/canais'
      fullPath: '/canais'
      preLoaderRoute: typeof CanaisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agente-ia': {
      id: '/agente-ia'
      path: '/agente-ia'
      fullPath: '/agente-ia'
      preLoaderRoute: typeof AgenteIaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas/': {
      id: '/propostas/'
      path: '/propostas'
      fullPath: '/propostas/'
      preLoaderRoute: typeof PropostasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/propostas/$id': {
      id: '/propostas/$id'
      path: '/propostas/$id'
      fullPath: '/propostas/$id'
      preLoaderRoute: typeof PropostasIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgenteIaRoute: AgenteIaRoute,
  CanaisRoute: CanaisRoute,
  CondicoesComerciaisRoute: CondicoesComerciaisRoute,
  ContatosRoute: ContatosRoute,
  PipelineRoute: PipelineRoute,
  ProdutosRoute: ProdutosRoute,
  TarefasRoute: TarefasRoute,
  PropostasIdRoute: PropostasIdRoute,
  PropostasIndexRoute: PropostasIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
